In [1]:
import numpy as np

arr = np.arange(1, 21)
matrix = arr.reshape(4, 5)

print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [2]:
import numpy as np

matrix = np.random.randint(1, 101, (5, 5))

print("Matrix:\n", matrix)
print("Min =", np.min(matrix))
print("Max =", np.max(matrix))

Matrix:
 [[ 63  92   1  99  68]
 [ 69  99  83  64  41]
 [ 30  66  41  30  95]
 [ 61  26  78  12 100]
 [ 42  98  77  88  83]]
Min = 1
Max = 100


In [3]:
import numpy as np

arr = np.arange(1, 11)

arr[arr % 2 == 0] = 0

print(arr)

[1 0 3 0 5 0 7 0 9 0]


In [4]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

result = np.dot(A, B)

print(result)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [5]:
import numpy as np

arr = np.arange(1, 26).reshape(5, 5)

sub_matrix = arr[1:4, 1:4]

print(sub_matrix)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [6]:
import numpy as np

matrix = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [13,14,15,16]])

row_sum = np.sum(matrix, axis=1)
col_sum = np.sum(matrix, axis=0)

print("Row Sum:", row_sum)
print("Column Sum:", col_sum)

Row Sum: [10 26 42 58]
Column Sum: [28 32 36 40]


In [7]:
import numpy as np

arr = np.arange(1, 16)

result = arr[arr > 10]

print(result)

[11 12 13 14 15]


In [8]:
import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

transpose = matrix.T

print(transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [9]:
import numpy as np

arr = np.random.rand(10)

normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

print("Original:", arr)
print("Normalized:", normalized)

Original: [0.85139336 0.82578176 0.91161164 0.33678123 0.31490125 0.07927916
 0.47681632 0.61608615 0.65856376 0.58492319]
Normalized: [0.92765117 0.89688029 1.         0.30937405 0.2830865  0.
 0.47761822 0.64494297 0.69597741 0.60750246]


In [10]:
import numpy as np

arr = np.arange(1, 11)

reversed_arr = arr[::-1]

print(reversed_arr)

[10  9  8  7  6  5  4  3  2  1]
